baseURL = 'https://blog.mdoff.net/'
languageCode = 'en-us'
title = "mdoff's blog"
theme = 'paper'
disqusShortname = 'blog-mdoff'

[author]
  name = 'Tomasz Lewiński'

[params]
  github = 'mdoff'
  mastodon = 'https://social.lol/@mdoff'
  rss = true

  author = 'Tomasz Lewiński'
  name = 'Tomasz Lewiński'
  bio = 'Software developer, mostly.'
  avatar = 'lewinski.tomasz@gmail.com'
  description = 'Hello there'
