# Header
menu:
  Home: /
  Archives: /archives
  'About me': '/about-me/'
  Contact: /contact/
rss: /atom.xml

# Content
excerpt_link: Read More
image_dir: images

# Miscellaneous
favicon: images/favicon.ico
